Update realm.php
This should fix a error navigatint to /admin/realms/?realm_id=<realm_id>
The error message is:
RuntimeError: Key "oids" for sequence/mapping with keys "display_name, ssid" does not exist.

There seems to be missing oids and nai_realms if using a NetworkSSID object